#!/bin/bash

disabled="disabled"
default_vpn="PIA+ - US East"
ssid_dir="networks"
counter_reset=360
nmcli_cmd="show"
autovpn_dir="$HOME/bin/autovpn"
if [ $(hostname) = "bb3" ]; then
	nmcli_cmd="status"
	default_vpn="PIA - US Texas"
fi

x="$counter_reset"
countEm() {
	if [ $x -ge $counter_reset ]; then
		echo "$1"
		x=0		
	else
		x=$((x+1))
	fi
}
getNetwork() {
	essid="$(iwgetid -r)"
	if [ "$essid" = '' ]; then
		countEm "No wireless network, switching to wired..." 
		essid="$(ip link | grep 'state UP' | cut -d' ' -f2 | sed s/://g)"
	fi
	if [ ! -d "$autovpn_dir/$ssid_dir" ]; then
		mkdir -p "$autovpn_dir/$ssid_dir"
	fi
	if [ ! -f "$autovpn_dir/$ssid_dir/$essid" ]; then
		echo "$default_vpn" | tee "$autovpn_dir/$ssid_dir/$essid"
	fi
}

while true; do
	getNetwork
	vpn_name="$(cat "$autovpn_dir/$ssid_dir/$essid")"
	if [ "$vpn_name" = "$disabled" ]; then
		countEm "AutoVPN autoconnect is user-disabled."
	else
		vpncon="$(nmcli con $nmcli_cmd id "$vpn_name" | grep VPN.VPN-STATE | awk '{print $2}')"
		if [ ! "$vpncon" = "5" ]; then
			echo "VPN disconnected, trying to reconnect..."
			(sleep 1s && nmcli con up id "$vpn_name")
		else
			countEm "AutoVPN has already connected :-)"
		fi
	fi
	sleep 1
done
